language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
install:
  - sudo pip install conda
  - sudo conda init
  - sudo conda update conda --yes
  - deps='pip numpy scipy coverage'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - python setup.py install
script: nosetests -v
notifications:
  email:
    false
